// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfovVhdmr-q7J3Fx4GOepgNnhzd1Cc2bc',
    appId: '1:1081477819784:web:59950dee57bb2375331e3d',
    messagingSenderId: '1081477819784',
    projectId: 'mihnati3',
    authDomain: 'mihnati3.firebaseapp.com',
    storageBucket: 'mihnati3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7UT9vwuvyqwvL-2MbJVFsRoqJhB3ofdo',
    appId: '1:1081477819784:android:69b938eda125b213331e3d',
    messagingSenderId: '1081477819784',
    projectId: 'mihnati3',
    storageBucket: 'mihnati3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmk1CDTaQZ1MLfdr7kyLki1FwA7manpmM',
    appId: '1:1081477819784:ios:5775d519747edae3331e3d',
    messagingSenderId: '1081477819784',
    projectId: 'mihnati3',
    storageBucket: 'mihnati3.firebasestorage.app',
    iosBundleId: 'com.example.mihnati2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmk1CDTaQZ1MLfdr7kyLki1FwA7manpmM',
    appId: '1:1081477819784:ios:5775d519747edae3331e3d',
    messagingSenderId: '1081477819784',
    projectId: 'mihnati3',
    storageBucket: 'mihnati3.firebasestorage.app',
    iosBundleId: 'com.example.mihnati2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfovVhdmr-q7J3Fx4GOepgNnhzd1Cc2bc',
    appId: '1:1081477819784:web:19b4a21b3eb3fda6331e3d',
    messagingSenderId: '1081477819784',
    projectId: 'mihnati3',
    authDomain: 'mihnati3.firebaseapp.com',
    storageBucket: 'mihnati3.firebasestorage.app',
  );
}
